package RemotoApp;

/**
* RemotoApp/RemotoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemotoApp.idl
* Segunda-feira, 10 de Outubro de 2022 20h11min48s BRT
*/

public final class RemotoHolder implements org.omg.CORBA.portable.Streamable
{
  public RemotoApp.Remoto value = null;

  public RemotoHolder ()
  {
  }

  public RemotoHolder (RemotoApp.Remoto initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RemotoApp.RemotoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RemotoApp.RemotoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RemotoApp.RemotoHelper.type ();
  }

}
