package RemotoApp;


/**
* RemotoApp/RemotoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemotoApp.idl
* Segunda-feira, 10 de Outubro de 2022 20h11min48s BRT
*/

abstract public class RemotoHelper
{
  private static String  _id = "IDL:RemotoApp/Remoto:1.0";

  public static void insert (org.omg.CORBA.Any a, RemotoApp.Remoto that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RemotoApp.Remoto extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (RemotoApp.RemotoHelper.id (), "Remoto");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RemotoApp.Remoto read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RemotoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RemotoApp.Remoto value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static RemotoApp.Remoto narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RemotoApp.Remoto)
      return (RemotoApp.Remoto)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      RemotoApp._RemotoStub stub = new RemotoApp._RemotoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static RemotoApp.Remoto unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RemotoApp.Remoto)
      return (RemotoApp.Remoto)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      RemotoApp._RemotoStub stub = new RemotoApp._RemotoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
