package RemotoApp;


/**
* RemotoApp/RemotoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemotoApp.idl
* Segunda-feira, 10 de Outubro de 2022 20h11min48s BRT
*/

public interface RemotoOperations 
{
  int raizQuadrada (int num);
  int fatorial (int num);
  int menorNum (int num1, int num2, int num3);
} // interface RemotoOperations
