package RemotoApp;


/**
* RemotoApp/RemotoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemotoApp.idl
* Segunda-feira, 10 de Outubro de 2022 20h11min48s BRT
*/

public abstract class RemotoPOA extends org.omg.PortableServer.Servant
 implements RemotoApp.RemotoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("raizQuadrada", new java.lang.Integer (0));
    _methods.put ("fatorial", new java.lang.Integer (1));
    _methods.put ("menorNum", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // RemotoApp/Remoto/raizQuadrada
       {
         int num = in.read_long ();
         int $result = (int)0;
         $result = this.raizQuadrada (num);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // RemotoApp/Remoto/fatorial
       {
         int num = in.read_long ();
         int $result = (int)0;
         $result = this.fatorial (num);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // RemotoApp/Remoto/menorNum
       {
         int num1 = in.read_long ();
         int num2 = in.read_long ();
         int num3 = in.read_long ();
         int $result = (int)0;
         $result = this.menorNum (num1, num2, num3);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:RemotoApp/Remoto:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Remoto _this() 
  {
    return RemotoHelper.narrow(
    super._this_object());
  }

  public Remoto _this(org.omg.CORBA.ORB orb) 
  {
    return RemotoHelper.narrow(
    super._this_object(orb));
  }


} // class RemotoPOA
